backend:
  name: git-gateway
  #name: github
  repo: key2victory/breakanchor
  branch: main # master # Branch to update (optional; defaults to master)
  #backend: local_backend
# This line should *not* be indented
#publish_mode: editorial_workflow

site_url: https://breakanchor.com/

# This line should *not* be indented
media_folder: "public/img/" # Media files will be stored in the repo under images/uploads

# These lines should *not* be indented
#media_folder: "static/img/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/public/img/" # The src attribute for uploaded media will begin with /images/uploads

# {{slug}}: a url-safe version of the title field (or identifier field) for the file
# {{year}}: 4-digit year of the file creation date
# {{month}}: 2-digit month of the file creation date
# {{day}}: 2-digit day of the month of the file creation date
# {{hour}}: 2-digit hour of the file creation date
# {{minute}}: 2-digit minute of the file creation date
# {{second}}: 2-digit second of the file creation date

collections:
  - name: "case-studies" # Used in routes, e.g., /admin/collections/blog
    label: "Case Studies" # Used in the UI
    folder: "/posts" # The path to the folder where the documents are stored
    extension: "md" #
    format: "frontmatter"
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Path", name: "path", widget: "string", hint: 'breakanchor.com/{path}'}
      - {label: "Title", name: "title", widget: "string", tagname: 'h1'}
      - {label: "Subtitle", name: "subtitle", widget: "string", tagname: 'h2', required: false}
      - {label: "Order", name: "order", widget: "number", default: 0, value_type: "int", min: 0, step: 1,}
      - {label: "Last Updated", name: "updated", widget: "datetime"}
      - {label: "Start Date", name: "start", widget: "datetime"}
      - {label: "End Date", name: "end", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Type", name: "type", widget: "select", multiple: true, options: ["case study", "presentation", "research", "design", "articles"], default: ["design"]}
      - {label: "Body", name: "body", widget: "markdown"}